name: Run Meeting Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute analysis script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
        - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'GitHub Action Failed: Meeting Analysis Bot'
          to: user1@example.com,user2@example.com
          from: GitHub Actions Bot
          body: |
            The Meeting Analysis workflow failed.
            Repository: ${{ github.repository }}
            See the run details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
